username=input('Введите имя пользователя ')
title=input('Введите название заметки ')
content=input('Введите текст ')
status=input("Введите статус задачи ")
created_date=input("Дата создания'дд.мм.гггг'")
issue_date=input("Дата истечения заметки'дд.мм.гггг'")

print(username)
print(title)
print(content)
print(status)
print(created_date)
print(issue_date)